### ISSUE TITLE
Release event

### ISSUE THREAD

**Issue by dnlmzw** [PopSugar/angular-slider#12]
Hi there. Thanks for your work with maintaining the slider.

I'm using the it for filtering some data, which is fetched via an HTTP request. Is there a way to listen on when the handle has been released so that the request isn't sent continuously?

Ng-mouseup listen on the entire slider, and doesn't account for releasing outside.

**Comment by that70schris** [comment]
@dnlmzw, try using `dragstop="true"`

**Comment by dnlmzw** [comment]
How do get the updated values while it is moving? I still want them to be outputted, just not changing until dragstop.
