### ISSUE TITLE
Error when moving slider over the left end

### ISSUE THREAD

**Issue by marcelboettcher** [PopSugar/angular-slider#13]
Hey,

thanks for keeping this project up and running!
I get an error on desktop browser, when dragging the slider further left than allowed - over the end.

The errors is caused by event.touches[0] as this does not exist:
`eventX = event.clientX || event.touches[0].clientX;`
https://github.com/PopSugar/angular-slider/blob/125db24239ab3e44c587c3682c867c29be541ee3/slider.js#L226

 Should be solved by checking if touches exists: 
`eventX = event.touches && event.touches.length > 0 ? event.touches[0].clientX : event.clientX; `

Thanks a lot!
Marcel

**Comment by that70schris** [comment]
@marcelboettcher this has been fixed in v0.2.11, thanks!

**Comment by marcelboettcher** [comment]
Thx, but now I'm getting an undefined function error at _.isInt
`  contain = function(value) {
    if (_.isInt(value)) {`

**Comment by marcelboettcher** [comment]
@that70schris do you get the same error? Any Idea? Thanks!

**Comment by that70schris** [comment]
@marcelboettcher please try the latest version v0.2.14

**Comment by marcelboettcher** [comment]
@that70schris thx! Works fine now!
