### ISSUE TITLE
Slider handles and range bar out of place on browser refresh

### ISSUE THREAD

**Issue by unscsprt** [PopSugar/angular-slider#20]
This isn't really an issue, as it doesn't happen all the time. I've had the same problem before and was able to fix it, but I forget how. Has anyone else ever encountered this, where parts of the slider are out of place when the page first loads, but snap to the correct positions when you click on one of the handles?

![screen shot 2015-01-23 at 2 43 24 pm](https://cloud.githubusercontent.com/assets/3260642/5881351/3bb9b04a-a30e-11e4-87f0-b1d49a658350.png)

Edit: This may actually be an issue (or maybe I'm loading scripts wrong, who knows), but I discovered something else. The slider loads fine when I go from one view in the app to the page that it's on, but I get this weird effect when refreshing the browser when on this page. Here's how I'm using it:

```
# signup.jade
slider(floor="10", ceiling="250", step="5", ng-model-low="newJob.salary_min", ng-model-high="newJob.salary_max")
```

And here's how I'm setting the initial values in the controller:

```
# signup.coffee
$scope.newJob =
    ...
    salary_min: 50
    salary_max: 150
```

**Comment by Hendrixer** [comment]
Is it because the templates are cached by angular after you've navigated to them? This might have to do with FUOC. Use an `ng-bind` or `ng-cloak` and se if that foxes it. BTW, i hvae never looked at this code and can be completely wrong, just based off your symptoms and offering some general troubleshooting.
